### ISSUE TITLE
Failed to send/process 'Get Cookies' request

### ISSUE THREAD

**Issue by cyberbiosecurity** [Exponefrv1/univk_audio#2]
Hello.
System info: Windows 10; Python 3.10.9
luxvk.com is available through web browser, so this is not a routing\network access problem.

I had installed univk_audio via pip.
Then I had modified auth_example.py and auth_with_example.py, assigning my vk.com creds to the following variables:
```
async def get_auth_cookies_example():
    login: str = "7995*****32"
    password: str = "KAafbkaj3as"
```

After that, upon running both auth_with_example.py and auth_example.py, I get the following error message:
Traceback (most recent call last):

>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\univk_audio\async_auth.py", line 229, in __send_get_cookies_request
>     async with self._session.get(
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 1167, in __aenter__
>     self._resp = await self._coro
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client.py", line 534, in _request
>     req = self._request_class(
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\client_reqrep.py", line 280, in __init__
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\yarl\_url.py", line 1012, in with_query
>     new_query = self._get_str_query(*args, **kwargs) or ""
>     query = "&".join(self._query_seq_pairs(quoter, query.items()))
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\yarl\_url.py", line 935, in _query_seq_pairs
>     yield quoter(key) + "=" + quoter(cls._query_var(val))
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\yarl\_url.py", line 951, in _query_var
>     raise TypeError(
> TypeError: Invalid variable type: value should be str, int or float, got None of type <class 'NoneType'>
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "C:\Users\cocolacre\repos\univk_audio\examples\auth_example.py", line 23, in <module>
>     asyncio.run(get_auth_cookies_example())
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "C:\Users\cocolacre\repos\univk_audio\examples\auth_example.py", line 18, in get_auth_cookies_example
>     cookies = await auth.get_auth_cookies(path = "cookies.txt")
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\univk_audio\async_auth.py", line 270, in get_auth_cookies
>     raise err
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\univk_audio\async_auth.py", line 263, in get_auth_cookies
>     cookie_string = await self.__send_get_cookies_request()
>   File "C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\univk_audio\async_auth.py", line 237, in __send_get_cookies_request
>     raise GetCookiesRequestError("Failed to send/process 'Get Cookies' request") from err
> univk_audio.auth_exceptions.GetCookiesRequestError: Failed to send/process 'Get Cookies' request

I've added some dirty debug print() to the mentioned modules, e.g.:
C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\univk_audio\**async_auth.py** line 221(in **try** block of **__send_get_cookies_request** coroutine:
```
self._req_data.links[4]=http://luxvk.com/, type(...)=<class 'str'>
self._req_data.code=None, type(...)=<class 'NoneType'>
```
in **_query_var** method in C:\Users\cocolacre\AppData\Local\Programs\Python\Python310\lib\site-packages\**yarl\_url.py** file :

> v=None   type(v)=<class 'NoneType'>

How can I help more in debugging the issue? Thank you.

**Comment by Exponefrv1** [comment]
**Hello, [cocolacre](https://github.com/cocolacre).**
Thank you for opening this issue.
There is a problem with hash parameter in "**oauth_code_data**" and "**__send_oauth_code_reques**".
I will fix this asap.

**If you really need it to work now - change hash parameter on string 72 in "request_data.py" file to value "5fd509994f872859e4".**

Appreciate your commit in my project :)

**Comment by Exponefrv1** [comment]
**Fixed.**
I won't upload it on pypi for a while, because **probably** there is a few more problems (with searching and downloading music).

**<3**
